name: neuroscan_ai
description: "MRI brain tumor classifier powered by AI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  firebase_messaging: ^15.2.1
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  tflite_flutter: ^0.11.0
  image_picker: ^1.1.2
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.4.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.19.0
  pdf: ^3.11.2
  printing: ^5.13.4
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter

flutter:
  assets:
    - assets/models/brain_tumor_model.tflite
    - assets/models/labels.txt

  uses-material-design: true
