import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../../../shared/models/scan_item.dart';

class PdfGenerator {
  static Future<Uint8List> generate(ScanItem item, Uint8List? imageBytes) async {
    final pdf = pw.Document();
    final description = _getDescription(item.resultType);
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Header(text: 'NEUROSCAN AI', level: 0),
            pw.Header(text: 'CONFIDENTIAL MEDICAL REPORT', level: 1),
            pw.Text('Diagnosis: ${item.resultType}'),
            pw.Text('Confidence: ${item.confidence.toStringAsFixed(1)}%'),
            if (imageBytes != null) pw.Image(pw.MemoryImage(imageBytes), height: 200),
            pw.SizedBox(height: 16),
            pw.Text('Clinical Notes', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            pw.Text(description),
            pw.SizedBox(height: 16),
            pw.Text('Confidence Scores', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            _scoreBar('Glioma', item.gliomaScore),
            _scoreBar('Meningioma', item.meningiomaScore),
            _scoreBar('Pituitary Tumor', item.pituitaryScore),
            _scoreBar('No Tumor', item.noTumorScore),
            pw.SizedBox(height: 24),
            pw.Container(
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(color: PdfColors.grey200, borderRadius: pw.BorderRadius.circular(8)),
              child: pw.Text('DISCLAIMER: This prediction is generated by an AI model. It is not a definitive diagnosis and MUST be reviewed by a certified medical professional.', style: const pw.TextStyle(fontSize: 9)),
            ),
          ],
        ),
      ),
    );
    return pdf.save();
  }

  static pw.Widget _scoreBar(String label, double score) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [pw.Text(label), pw.Text('${score.toStringAsFixed(1)}%')]),
        pw.SizedBox(height: 2),
        pw.Container(
          height: 8,
          decoration: pw.BoxDecoration(color: PdfColors.grey300, borderRadius: pw.BorderRadius.circular(4)),
          child: pw.Align(
            alignment: pw.Alignment.centerLeft,
            child: pw.Container(width: (score / 100).clamp(0.0, 1.0) * 500, height: 8, color: PdfColors.blue700),
          ),
        ),
        pw.SizedBox(height: 8),
      ],
    );
  }

  static String _getDescription(String type) {
    return switch (type) {
      'Glioma' => 'A primary brain tumor that originates from the glial cells in the brain or spinal cord.',
      'Meningioma' => 'A tumor that arises from the meninges, the membranes that surround the brain and spinal cord. Most are slow-growing and benign.',
      'Pituitary Tumor' => 'An abnormal growth in the pituitary gland. Most are noncancerous adenomas that may affect hormone levels.',
      'No Tumor' => 'The scan appears clear of these specific tumor types.',
      _ => 'Information not available.',
    };
  }
}
